<a href="https://colab.research.google.com/github/ramesitexp/Python_Zone/blob/main/PandasOperationV2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data link
#data link - https://drive.google.com/drive/folders/1zauEUoewFclurlYCh89FHgDfW9is6Y_r?usp=share_link

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("/content/addresses.csv")

In [ ]:
data

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
8,9,9,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
9,10,10,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
10,11,11,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US
11,12,12,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
12,13,13,399 Marine Parkway.,NaN,Redwood City,CA,94065,US
13,14,14,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US
14,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
data.head()

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US

In [ ]:
data.head(6)

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US

In [ ]:
data.tail()

,id,location_id,address_1,address_2,city,state_province,postal_code,country
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [ ]:
data.tail(7)

,id,location_id,address_1,address_2,city,state_province,postal_code,country
14,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [ ]:
data.columns

Index(['id', 'location_id', 'address_1', 'address_2', 'city', 'state_province',
       'postal_code', 'country'],
      dtype='object')

In [ ]:
list(data.columns)

['id',
 'location_id',
 'address_1',
 'address_2',
 'city',
 'state_province',
 'postal_code',
 'country']

In [ ]:
data[['id','address_1']]

    id                   address_1
0    1       2600 Middlefield Road
1    2            24 Second Avenue
2    3            24 Second Avenue
3    4            24 Second Avenue
4    5            24 Second Avenue
5    6           800 Middle Avenue
6    7              500 Arbor Road
7    8           800 Middle Avenue
8    9       2510 Middlefield Road
9   10       1044 Middlefield Road
10  11         2140 Euclid Avenue.
11  12       1044 Middlefield Road
12  13         399 Marine Parkway.
13  14          660 Veterans Blvd.
14  15        1500 Valencia Street
15  16         1161 South Bernardo
16  17     409 South Spruce Avenue
17  18            114 Fifth Avenue
18  19         19 West 39th Avenue
19  20          123 El Camino Real
20  21  2013 Avenue of the fellows

In [ ]:
data[['city','location_id ']]

                   city  location_id
0          Redwood City            1
1             San Mateo            2
2             San Mateo            3
3             San Mateo            4
4             San Mateo            5
5            Menlo Park            6
6            Menlo Park            7
7            Menlo Park            8
8          Redwood City            9
9          Redwood City           10
10         Redwood City           11
11         Redwood City           12
12         Redwood City           13
13         Redwood City           14
14        San Francisco           15
15            Sunnyvale           16
16  South San Francisco           17
17         Redwood City           18
18            San Mateo           19
19              Belmont           21
20        San Francisco           22

In [ ]:
data['state_province']

0     CA
1     CA
2     CA
3     CA
4     CA
5     CA
6     CA
7     CA
8     CA
9     CA
10    CA
11    CA
12    CA
13    CA
14    CA
15    CA
16    CA
17    CA
18    CA
19    CA
20    CA
Name: state_province, dtype: object

In [ ]:
type(data['state_province'])

pandas.core.series.Series

In [ ]:
data[['state_province']]

   state_province
0              CA
1              CA
2              CA
3              CA
4              CA
5              CA
6              CA
7              CA
8              CA
9              CA
10             CA
11             CA
12             CA
13             CA
14             CA
15             CA
16             CA
17             CA
18             CA
19             CA
20             CA

In [ ]:
type(data[['state_province']])

pandas.core.frame.DataFrame

In [ ]:
data['city','location_id ']

KeyError: ('city', 'location_id ')

In [ ]:
data1=pd.read_excel('/content/airline.xls')

In [ ]:
data1

    YEAR       Y      W       R      L      K
0   1948   1.214  0.243  0.1454  1.415  0.612
1   1949   1.354  0.260  0.2181  1.384  0.559
2   1950   1.569  0.278  0.3157  1.388  0.573
3   1951   1.948  0.297  0.3940  1.550  0.564
4   1952   2.265  0.310  0.3559  1.802  0.574
5   1953   2.731  0.322  0.3593  1.926  0.711
6   1954   3.025  0.335  0.4025  1.964  0.776
7   1955   3.562  0.350  0.3961  2.116  0.827
8   1956   3.979  0.361  0.3822  2.435  0.800
9   1957   4.420  0.379  0.3045  2.707  0.921
10  1958   4.563  0.391  0.3284  2.706  1.067
11  1959   5.385  0.426  0.3856  2.846  1.083
12  1960   5.554  0.441  0.3193  3.089  1.481
13  1961   5.465  0.460  0.3079  3.122  1.736
14  1962   5.825  0.485  0.3783  3.184  1.926
15  1963   6.876  0.506  0.4180  3.263  2.041
16  1964   7.823  0.538  0.5163  3.412  1.997
17  1965   9.120  0.564  0.5879  3.623  2.257
18  1966  10.512  0.586  0.5369  4.074  2.742
19  1967  13.020  0.622  0.4443  4.710  3.564
20  1968  15.261  0.666  0.3052  5.217  4.767
21  1969  16.313  0.731  0.2332  5.569  6.511
22  1970  16.002  0.831  0.1883  5.495  7.627
23  1971  15.876  0.906  0.2023  5.334  8.673
24  1972  16.662  1.000  0.2506  5.345  8.331
25  1973  17.014  1.056  0.2668  5.662  8.557
26  1974  19.305  1.131  0.2664  5.729  9.508
27  1975  18.721  1.247  0.2301  5.722  9.062
28  1976  19.250  1.375  0.3452  5.762  8.262
29  1977  20.647  1.544  0.4508  5.877  7.474
30  1978  22.726  1.703  0.5877  6.108  7.104
31  1979  23.619  1.779  0.5346  6.852  6.874

In [ ]:
data1.describe()

              YEAR          Y          W          R          L          K
count    32.000000  32.000000  32.000000  32.000000  32.000000  32.000000
mean   1963.500000  10.050187   0.691344   0.354931   3.793375   3.736281
std       9.380832   7.255404   0.441908   0.115031   1.708000   3.304078
min    1948.000000   1.214000   0.243000   0.145400   1.384000   0.559000
25%    1955.750000   3.874750   0.358250   0.266700   2.355250   0.820250
50%    1963.500000   7.349500   0.522000   0.350550   3.337500   2.019000
75%    1971.250000  16.400250   0.929500   0.406375   5.513500   7.196500
max    1979.000000  23.619000   1.779000   0.587900   6.852000   9.508000

In [ ]:
data=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

NameError: name 'pd' is not defined

In [ ]:
data.tail(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
   data.dtypes=="object"

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [ ]:
data.dtypes[data.dtypes=="object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [ ]:
 data [data.dtypes[data.dtypes=="object"].index].describe()

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [ ]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
data[(data['Survived']==0) & (data['Sex']=='male')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
data[(data['Survived']==0) & (data['Sex']=='male')].count()

PassengerId    468
Survived       468
Pclass         468
Name           468
Sex            468
Age            360
SibSp          468
Parch          468
Ticket         468
Fare           468
Cabin           62
Embarked       468
dtype: int64

In [ ]:
len(data[(data['Survived']==0) & (data['Sex']=='male')])

468

In [ ]:
len(data[(data['Survived']==0) & (data['Sex']=='female')])

81

In [ ]:
data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [ ]:
max(data['Fare'])

512.3292

In [ ]:
data[data['Fare']==max(data['Fare'])][['Name']]

                                   Name
258                    Ward, Miss. Anna
679  Cardeza, Mr. Thomas Drake Martinez
737              Lesurer, Mr. Gustave J

In [ ]:
data[data['Fare']==min(data['Fare'])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
179,180,0,3,"Leonard, Mr. Lionel",male,36.0,0,0,LINE,0.0,NaN,S
263,264,0,1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0,B94,S
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0,NaN,S
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0,NaN,S
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0,NaN,S
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0,NaN,S
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0,NaN,S
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0,NaN,S
597,598,0,3,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0,NaN,S
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0,NaN,S
674,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0,NaN,S
732,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0,NaN,S
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0,A36,S
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0,B102,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0,NaN,S

In [ ]:
data[data['Cabin'].isnull()==False]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
len(data[data['Cabin'].isnull()==False])

204

In [ ]:
data['new_col']='ram'

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,ram
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,ram
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,ram
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,ram
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,ram
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,ram
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,ram
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,ram
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,ram
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,ram

In [ ]:
data['Name_new']=data['Name']

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,Name_new
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,ram,"Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,ram,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,ram,"Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,ram,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,ram,"Allen, Mr. William Henry"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,ram,"Montvila, Rev. Juozas"
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,ram,"Graham, Miss. Margaret Edith"
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,ram,"Johnston, Miss. Catherine Helen ""Carrie"""
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,ram,"Behr, Mr. Karl Howell"
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,ram,"Dooley, Mr. Patrick"

In [ ]:
data['age_Pclass']=data['Age']+data['Pclass']

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,Name_new,age_Pclass
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,ram,"Braund, Mr. Owen Harris",25.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,ram,"Cumings, Mrs. John Bradley (Florence Briggs Th...",39.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,ram,"Heikkinen, Miss. Laina",29.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,ram,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",36.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,ram,"Allen, Mr. William Henry",38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,ram,"Montvila, Rev. Juozas",29.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,ram,"Graham, Miss. Margaret Edith",20.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,ram,"Johnston, Miss. Catherine Helen ""Carrie""",NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,ram,"Behr, Mr. Karl Howell",27.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,ram,"Dooley, Mr. Patrick",35.0

In [ ]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,Name_new,age_Pclass
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,ram,"Braund, Mr. Owen Harris",25.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,ram,"Cumings, Mrs. John Bradley (Florence Briggs Th...",39.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,ram,"Heikkinen, Miss. Laina",29.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,ram,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",36.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,ram,"Allen, Mr. William Henry",38.0

In [ ]:
data.drop('new_col',axis=1,inplace=True)

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name_new,age_Pclass
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"Braund, Mr. Owen Harris",25.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"Cumings, Mrs. John Bradley (Florence Briggs Th...",39.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"Heikkinen, Miss. Laina",29.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",36.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,"Allen, Mr. William Henry",38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,"Montvila, Rev. Juozas",29.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,"Graham, Miss. Margaret Edith",20.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,"Johnston, Miss. Catherine Helen ""Carrie""",NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,"Behr, Mr. Karl Howell",27.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,"Dooley, Mr. Patrick",35.0

In [ ]:
data=data.drop(0)

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name_new,age_Pclass
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"Cumings, Mrs. John Bradley (Florence Briggs Th...",39.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"Heikkinen, Miss. Laina",29.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",36.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,"Allen, Mr. William Henry",38.0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,"Moran, Mr. James",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,"Montvila, Rev. Juozas",29.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,"Graham, Miss. Margaret Edith",20.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,"Johnston, Miss. Catherine Helen ""Carrie""",NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,"Behr, Mr. Karl Howell",27.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,"Dooley, Mr. Patrick",35.0

In [ ]:
data[data['PassengerId']]